import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/adatvedelem")({
  head: () => ({ meta: [
    { title: "Adatvédelem | BioCare Kozmetika" },
    { name: "description", content: "Tájékoztatás a BioCare Kozmetika weboldalán megadott adatok kezeléséről." },
    { property: "og:title", content: "Adatvédelem | BioCare Kozmetika" },
    { property: "og:description", content: "Tájékoztatás a BioCare Kozmetika weboldalán megadott adatok kezeléséről." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ] }),
  component: Adatvedelem,
});

function Adatvedelem() {
  return <main className="min-h-screen bg-background px-6 py-12 text-foreground"><div className="mx-auto max-w-3xl">
    <Link to="/" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft size={16}/> Vissza a főoldalra</Link>
    <p className="mt-20 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">BioCare Kozmetika</p>
    <h1 className="mt-4 font-display text-5xl">Adatkezelési és adatvédelmi tájékoztató</h1>
    <div className="mt-6 space-y-5 leading-relaxed text-muted-foreground">
      <p><strong>BioCare Kozmetika – Miskolczi Dominika egyéni vállalkozó</strong></p>
      <p><strong>Hatályos:</strong> 2026. szeptember 27. napjától</p>
      <p>Jelen Adatkezelési és Adatvédelmi Tájékoztató célja, hogy a BioCare Kozmetika szolgáltatásait igénybe vevő vendégek, a weboldal látogatói, érdeklődők, időpontot foglaló személyek és egyéb érintettek világos és közérthető tájékoztatást kapjanak személyes adataik kezeléséről.</p>
      <p>Az Adatkezelő a személyes adatokat az Európai Parlament és a Tanács (EU) 2016/679 rendelete („GDPR”), a 2011. évi CXII. törvény („Infotv.”), valamint az egyéb vonatkozó magyar és európai uniós jogszabályok rendelkezéseinek megfelelően kezeli.</p>
      <p>Jelen tájékoztató a <a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a> weboldalon, továbbá a BioCare Kozmetikával történő kapcsolatfelvétel, időpontfoglalás és szolgáltatás-igénybevétel során végzett adatkezelésekre vonatkozik.</p>
    </div>
    <div className="mt-12 space-y-10 border-t border-border pt-8 leading-relaxed text-muted-foreground">
      <section><h2 className="font-display text-3xl text-foreground">1. Az adatkezelő adatai</h2><div className="mt-4 space-y-2"><p><strong>Adatkezelő neve:</strong> Miskolczi Dominika egyéni vállalkozó</p><p><strong>Kereskedelmi név:</strong> BioCare Kozmetika</p><p><strong>Adószám:</strong> 59869850-1-22</p><p><strong>Alapítás éve:</strong> 2023</p><p><strong>Főtevékenység:</strong> 9622 – Szépségápolás / kozmetikai, szépségápolási tevékenység</p><p><strong>Székhely:</strong> 7627 Pécs, Károly utca 11. 3. ajtó</p><p><strong>Telephelyek száma:</strong> 1</p><p><strong>Szolgáltatás helye / telephely:</strong> 7622 Pécs, Jókai u. 30.</p><p><strong>Weboldal:</strong> <a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a></p><p><strong>E-mail:</strong> <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a></p><p><strong>Telefon:</strong> +36 30 146 9885</p><p>Az adatkezeléssel kapcsolatos kérdések, kérelmek és panaszok a fenti e-mail-címen vagy postai úton az Adatkezelő székhelyére küldhetők.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">2. Az adatkezelés alapelvei</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő a személyes adatokat jogszerűen, tisztességesen és az érintett számára átlátható módon kezeli.</p><p>Az Adatkezelő kizárólag meghatározott, egyértelmű és jogszerű célból kezel személyes adatot, és csak olyan adatot kér, amely az adott cél eléréséhez szükséges.</p><p>A személyes adatokat az Adatkezelő csak a szükséges ideig őrzi meg, és megfelelő technikai, szervezési és biztonsági intézkedésekkel védi a jogosulatlan hozzáféréstől, megváltoztatástól, nyilvánosságra hozataltól, elvesztéstől vagy megsemmisüléstől.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">3. Kapcsolatfelvétel és érdeklődés</h2><div className="mt-4 space-y-4"><p>Az érintett telefonon, e-mailben, közösségi média felületen vagy a weboldalon keresztül kapcsolatba léphet a BioCare Kozmetikával.</p><p><strong>Kezelt adatok:</strong> név, telefonszám, e-mail-cím, az üzenet tartalma, valamint az érintett által önkéntesen megadott egyéb információ.</p><p><strong>Az adatkezelés célja:</strong> kapcsolatfelvétel, kérdések megválaszolása, tájékoztatás nyújtása, szolgáltatásokkal kapcsolatos egyeztetés és időpontfoglalás előkészítése.</p><p><strong>Jogalap:</strong> a GDPR 6. cikk (1) bekezdés b) pontja alapján az érintett kérésére történő, szerződéskötést megelőző intézkedések megtétele, illetve adott esetben a GDPR 6. cikk (1) bekezdés f) pontja szerinti jogos érdek.</p><p>Az olyan megkereséseket, amelyekből nem jön létre szolgáltatási jogviszony, az Adatkezelő indokolatlanul hosszú ideig nem őrzi meg.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">4. Időpontfoglalás</h2><div className="mt-4 space-y-4"><p>Időpontfoglalás történhet telefonon, e-mailben, személyesen, a weboldalon vagy – amennyiben ilyen rendszer bevezetésre kerül – online időpontfoglaló rendszeren vagy mobil/webalkalmazáson keresztül.</p><p><strong>Kezelt adatok:</strong> név, telefonszám, e-mail-cím, választott szolgáltatás, foglalás dátuma és időpontja, a foglaláshoz kapcsolódó megjegyzés, korábbi vagy módosított időpontokkal kapcsolatos információk.</p><p><strong>Az adatkezelés célja:</strong> időpont rögzítése és kezelése, a szolgáltatás megszervezése, az érintett azonosítása, kapcsolattartás, időpont módosítása vagy lemondása, valamint szükség esetén emlékeztető küldése.</p><p><strong>Jogalap:</strong> GDPR 6. cikk (1) bekezdés b) pont – szerződés teljesítése, illetve a szerződés megkötését megelőző lépések megtétele.</p><p>Az időpontfoglaláshoz szükséges adatok megadása nélkül az Adatkezelő nem minden esetben tudja a foglalást megfelelően rögzíteni vagy az érintettet az esetleges változásokról értesíteni.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">5. A kozmetikai szolgáltatás igénybevétele</h2><div className="mt-4 space-y-4"><p>A kezelések biztonságos és személyre szabott elvégzése érdekében az Adatkezelő bizonyos, a szolgáltatáshoz szükséges adatokat kezelhet.</p><p>Ide tartozhat különösen a vendég neve, elérhetősége, igénybe vett kezelése, kezelés időpontja, alkalmazott kozmetikai termékek, valamint a kezeléshez kapcsolódó szakmai feljegyzések.</p><p>Az adatkezelés elsődleges jogalapja a GDPR 6. cikk (1) bekezdés b) pontja, vagyis a szolgáltatás nyújtására irányuló szerződés teljesítése.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">6. Egészségi állapotra vonatkozó és különleges személyes adatok</h2><div className="mt-4 space-y-4"><p>Bizonyos kozmetikai kezelések biztonságos elvégzéséhez szükséges lehet olyan információ megadása, amely az érintett egészségi állapotára vonatkozik.</p><p>Ilyen információ lehet például valamely allergia, bőrérzékenység, bőrbetegség, gyógyszerérzékenység, várandósság, gyógyszerszedés vagy olyan korábbi állapot, amely befolyásolhatja egy adott kozmetikai kezelés biztonságos alkalmazását.</p><p>Az egészségi állapotra vonatkozó adat a GDPR értelmében különleges személyes adat.</p><p>Az Adatkezelő ilyen adatot kizárólag akkor kezel, amikor az adott kezelés szempontjából indokolt és szükséges.</p><p><strong>Jogalap:</strong> az érintett GDPR 9. cikk (2) bekezdés a) pontja szerinti <strong>kifejezett hozzájárulása</strong>, a szükséges GDPR 6. cikk szerinti jogalappal együtt.</p><p>A hozzájárulás önkéntes, konkrét és megfelelő tájékoztatáson alapul. Az érintett jogosult hozzájárulását bármikor visszavonni. A visszavonás nem érinti a visszavonás előtt végzett adatkezelés jogszerűségét.</p><p>Amennyiben valamely egészségi információ hiánya miatt egy kezelés biztonságosan nem végezhető el, az Adatkezelő jogosult a kezelést megtagadni vagy más kezelést javasolni.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">7. Számlázással és könyveléssel kapcsolatos adatkezelés</h2><div className="mt-4 space-y-4"><p>Számla kiállításakor az Adatkezelő a vonatkozó jogszabályok által előírt adatokat kezeli.</p><p><strong>Kezelt adatok:</strong> név, számlázási cím, valamint szükség esetén adószám és egyéb, számlázáshoz kötelező adat.</p><p><strong>Cél:</strong> számla kiállítása, számviteli és adózási kötelezettségek teljesítése.</p><p><strong>Jogalap:</strong> GDPR 6. cikk (1) bekezdés c) pont – az Adatkezelőre vonatkozó jogi kötelezettség teljesítése.</p><p>A számviteli bizonylatokat és a hozzájuk kapcsolódó személyes adatokat az Adatkezelő a jogszabályban előírt megőrzési időn, főszabály szerint <strong>legalább 8 éven keresztül</strong> őrzi meg.</p><p>Az ilyen adatok törlését az érintett a kötelező jogszabályi megőrzési idő alatt nem kérheti eredményesen.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">8. Panaszkezelés</h2><div className="mt-4 space-y-4"><p>A vendég a szolgáltatással kapcsolatos panaszát szóban vagy írásban is közölheti.</p><p><strong>Kezelt adatok:</strong> név, elérhetőség, panasz tartalma, panasz előterjesztésének ideje, az érintett által benyújtott dokumentumok és a panasz kivizsgálásához szükséges további információk.</p><p><strong>Az adatkezelés célja:</strong> panasz kivizsgálása, megválaszolása és a fogyasztóvédelmi előírások teljesítése.</p><p><strong>Jogalap:</strong> GDPR 6. cikk (1) bekezdés c) pont – jogi kötelezettség teljesítése.</p><p>Az írásbeli panaszt, illetve a szóbeli panaszról felvett jegyzőkönyvet és az arra adott érdemi választ az Adatkezelő a vonatkozó fogyasztóvédelmi szabályok alapján <strong>3 évig</strong> őrzi meg.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">9. Hírlevél, akciók és közvetlen marketing</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő reklám-, hírlevél-, kedvezmény- vagy promóciós üzenetet e-mailben vagy más közvetlen elektronikus kommunikációs csatornán természetes személy részére főszabály szerint csak az érintett előzetes, megfelelő és kifejezett hozzájárulása alapján küld.</p><p>A marketingcélú hozzájárulás nem lehet feltétele a kozmetikai szolgáltatás igénybevételének.</p><p>A hozzájárulás bármikor, ingyenesen és indokolás nélkül visszavonható.</p><p>A leiratkozás után az Adatkezelő az érintett részére további marketingcélú üzenetet nem küld, kivéve, ha az érintett később ismételten hozzájárul.</p><p>Az időpont-visszaigazolás, módosításról szóló értesítés vagy más, meglévő foglalással kapcsolatos üzenet nem minősül marketingcélú hírlevélnek.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">10. Fényképek, „előtte–utána” képek és közösségi média</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika kizárólag az érintett megfelelő hozzájárulásával készít és használ fel olyan fényképet vagy videófelvételt, amelyen az érintett felismerhető.</p><p>Különösen ide tartoznak az „előtte–utána” fényképek, vendégfotók, referenciaanyagok és közösségi média bejegyzések.</p><p>A kép elkészítéséhez való hozzájárulás és a kép nyilvános közzétételéhez adott hozzájárulás lehetőség szerint elkülönítetten kerül kezelésre.</p><p>Az érintett hozzájárulása visszavonható. A visszavonás után az Adatkezelő a saját ellenőrzése alatt álló felületekről a jövőre nézve eltávolítja a felvételt, amennyiben annak további kezelésére nincs más megfelelő jogalap.</p><p>Az internet sajátosságai miatt az Adatkezelő nem tudja garantálni olyan másolatok törlését, amelyeket a közzététel időtartama alatt független harmadik személyek jogellenesen vagy az Adatkezelő ellenőrzési körén kívül elmentettek vagy továbbítottak.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">11. A weboldal adatkezelése</h2><div className="mt-4 space-y-4"><p>A weboldal meglátogatásakor a webszerver és a weboldal működését biztosító informatikai rendszerek technikai adatokat kezelhetnek.</p><p>Ilyen adat lehet különösen az IP-cím, a látogatás időpontja, a használt böngésző és eszköz technikai adatai, az operációs rendszer típusa, a meglátogatott aloldalak és a rendszer működéséhez szükséges naplóadatok.</p><p>Az ilyen adatkezelés célja a weboldal biztonságos működésének biztosítása, informatikai hibák felismerése, jogosulatlan hozzáférések megelőzése és a rendszer biztonságának fenntartása.</p><p>Amennyiben a weboldal kapcsolatfelvételi vagy időpontfoglalási űrlapot tartalmaz, az űrlapon keresztül megadott adatok kezelésére a jelen tájékoztató megfelelő fejezetei alkalmazandók.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">12. Sütik – cookie-k</h2><div className="mt-4 space-y-4"><p>A weboldal működéséhez szükséges technikai sütik alkalmazhatók olyan mértékben, amennyiben azok a weboldal megfelelő működéséhez feltétlenül szükségesek.</p><p>Az olyan sütik vagy hasonló technológiák, amelyek statisztikai, analitikai, személyre szabási vagy marketingcélt szolgálnak, csak akkor aktiválhatók, ha az alkalmazásukhoz szükséges hozzájárulást a látogató előzetesen megadta.</p><p>A látogatónak lehetőséget kell biztosítani arra, hogy a nem szükséges sütiket elfogadja vagy elutasítsa, illetve korábbi hozzájárulását később megváltoztassa vagy visszavonja.</p><p>A weboldalon ténylegesen alkalmazott sütik pontos nevét, szolgáltatóját, célját és élettartamát a weboldal technikai beállításainak megfelelő külön süti-/cookie-tájékoztatóban vagy sütibeállító felületen szükséges feltüntetni.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">13. Közösségi oldalak</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika közösségi média oldalakat is használhat, ideértve különösen a Facebook és Instagram szolgáltatásokat.</p><p>Amennyiben az érintett ezeken a platformokon kapcsolatba lép a BioCare Kozmetikával, hozzászólást ír, üzenetet küld vagy más interakciót végez, az adott közösségi platform saját adatkezelési szabályai is alkalmazandók.</p><p>Az Adatkezelő kizárólag azokat az adatokat kezeli, amelyekhez az érintett közösségi médiában végzett tevékenysége következtében jogszerűen hozzáfér.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">14. Adatfeldolgozók és címzettek</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő a működéséhez szükséges mértékben adatfeldolgozókat és külső szolgáltatókat vehet igénybe.</p><p>Ilyen szolgáltató lehet különösen a könyvelő, számlázási rendszer szolgáltatója, tárhelyszolgáltató, weboldal-karbantartó, e-mail-szolgáltató, informatikai szolgáltató, valamint – amennyiben bevezetésre kerül – online időpontfoglaló rendszer vagy annak API-szolgáltatója.</p><p>Az Adatkezelő kizárólag olyan adatfeldolgozót vesz igénybe, amely megfelelő garanciákat nyújt a személyes adatok védelmére.</p><p><strong>Közzététel előtt ebben a pontban fel kell tüntetni a ténylegesen használt szolgáltatókat</strong>, különösen:</p><p><strong>Tárhelyszolgáltató:</strong> [KITÖLTENDŐ – szolgáltató neve, székhelye, elérhetősége]</p><p><strong>Számlázóprogram:</strong> [KITÖLTENDŐ – amennyiben elektronikus számlázó használatban van]</p><p><strong>Könyvelő / könyvelőiroda:</strong> [KITÖLTENDŐ, ha személyes adatokhoz hozzáfér]</p><p><strong>Online időpontfoglaló rendszer:</strong> [KITÖLTENDŐ – amennyiben bevezetésre kerül]</p><p>Ha a BioCare Kozmetika például saját webalkalmazásba külső időpontfoglaló szolgáltatás API-ját integrálja, annak szolgáltatóját és az érintett adatok kezelésének lényeges körülményeit a rendszer élesítése előtt ebben a tájékoztatóban is fel kell tüntetni.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">15. Adattovábbítás az Európai Gazdasági Térségen kívülre</h2><div className="mt-4 space-y-4"><p>Amennyiben az Adatkezelő olyan szolgáltatót vesz igénybe, amelynek alkalmazása során személyes adatok az Európai Gazdasági Térségen kívüli harmadik országba kerülhetnek továbbításra, az Adatkezelő gondoskodik arról, hogy az adattovábbítás a GDPR V. fejezetének megfelelő jogalapon és megfelelő garanciák mellett történjen.</p><p>Ilyen garancia lehet különösen az Európai Bizottság megfelelőségi határozata vagy az Európai Bizottság által elfogadott általános szerződési feltételek alkalmazása.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">16. Adatbiztonság</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő megfelelő technikai és szervezési intézkedéseket alkalmaz annak érdekében, hogy a személyes adatok biztonságát az adatkezelés teljes időtartama alatt biztosítsa.</p><p>Az Adatkezelő az adatokhoz történő hozzáférést a szükséges személyekre korlátozza, az elektronikus rendszereket megfelelő hozzáférésvédelemmel látja el, és törekszik az adatvesztés, jogosulatlan hozzáférés, módosítás vagy nyilvánosságra hozatal megelőzésére.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">17. Adatvédelmi incidens</h2><div className="mt-4 space-y-4"><p>Adatvédelmi incidensnek minősül többek között a személyes adatok véletlen vagy jogellenes megsemmisítése, elvesztése, megváltoztatása, jogosulatlan közlése vagy az adatokhoz való jogosulatlan hozzáférés.</p><p>Az Adatkezelő az adatvédelmi incidenst kivizsgálja és dokumentálja, és amennyiben a GDPR alapján szükséges, az incidenst a jogszabályban meghatározott határidőn belül bejelenti a Nemzeti Adatvédelmi és Információszabadság Hatóság részére.</p><p>Ha az incidens valószínűsíthetően magas kockázattal jár az érintett természetes személyek jogaira és szabadságaira nézve, az Adatkezelő a jogszabályban meghatározott esetekben az érintetteket is tájékoztatja.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">18. Az érintett jogai</h2><div className="mt-4 space-y-4"><p>Az érintett a GDPR feltételeinek megfelelően jogosult tájékoztatást kérni személyes adatai kezeléséről és hozzáférést kérni az Adatkezelő által kezelt személyes adataihoz.</p><p>Jogosult kérni pontatlan személyes adatainak helyesbítését, valamint a GDPR-ban meghatározott feltételek fennállása esetén személyes adatainak törlését vagy az adatkezelés korlátozását.</p><p>Meghatározott esetekben jogosult tiltakozni a személyes adatai kezelése ellen és jogosult lehet az adathordozhatósághoz.</p><p>Amennyiben az adatkezelés hozzájáruláson alapul, az érintett hozzájárulását bármikor visszavonhatja. A visszavonás nem érinti a korábban, a hozzájárulás alapján végzett adatkezelés jogszerűségét.</p><p>A törléshez való jog nem korlátlan. Az Adatkezelő nem köteles olyan adatot törölni, amelynek megőrzését jogszabály írja elő, vagy amelynek további kezelése jogi igény előterjesztéséhez, érvényesítéséhez vagy védelméhez szükséges.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">19. Az érintetti kérelmek teljesítése</h2><div className="mt-4 space-y-4"><p>Az adatvédelmi kérelem a <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a> e-mail-címre vagy az Adatkezelő székhelyére küldhető.</p><p>Az Adatkezelő a kérelmet indokolatlan késedelem nélkül, főszabály szerint a beérkezésétől számított <strong>egy hónapon belül</strong> megvizsgálja és tájékoztatja az érintettet a megtett intézkedésről.</p><p>A határidő a GDPR-ban meghatározott körülmények fennállása esetén további két hónappal meghosszabbítható. A hosszabbításról és annak indokáról az Adatkezelő az eredeti egy hónapos határidőn belül tájékoztatást ad.</p><p>Az Adatkezelő személyazonosság ellenőrzéséhez szükséges további információt kérhet, amennyiben megalapozott kétsége merül fel a kérelmet benyújtó személy személyazonosságával kapcsolatban.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">20. Automatizált döntéshozatal és profilalkotás</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika a szolgáltatásai nyújtása során főszabály szerint nem alkalmaz olyan kizárólag automatizált adatkezelésen alapuló döntéshozatalt, amely az érintettre nézve joghatással járna vagy őt hasonlóképpen jelentős mértékben érintené.</p><p>Amennyiben a jövőben ilyen rendszer kerülne bevezetésre, az Adatkezelő a használat megkezdése előtt megfelelően módosítja jelen tájékoztatót.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">21. Kiskorúak adatai</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika egyes szolgáltatásai – például tini kezelések – kiskorú vendégek számára is elérhetők lehetnek.</p><p>Kiskorú személy adatainak kezelésekor az Adatkezelő kiemelt figyelmet fordít a gyermekek személyes adatainak védelmére, és ahol az adott adatkezeléshez jogszabály alapján szükséges, a törvényes képviselő megfelelő közreműködését vagy hozzájárulását kéri.</p><p>Az Adatkezelő kiskorú személyről marketing-, referencia- vagy közösségi médiában történő közzététel céljából fényképet csak a vonatkozó jogszabályoknak megfelelő hozzájárulás birtokában használ fel.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">22. Jogorvoslati lehetőségek</h2><div className="mt-4 space-y-4"><p>Amennyiben az érintett úgy véli, hogy személyes adatainak kezelése sérti a vonatkozó adatvédelmi jogszabályokat, elsődlegesen az Adatkezelőhöz fordulhat:</p><p><strong>Miskolczi Dominika egyéni vállalkozó – BioCare Kozmetika</strong><br/>E-mail: <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a><br/>Székhely: 7627 Pécs, Károly utca 11. 3. ajtó</p><p>Az érintett jogosult panaszt tenni a felügyeleti hatóságnál is:</p><p><strong>Nemzeti Adatvédelmi és Információszabadság Hatóság (NAIH)</strong><br/>Székhely: 1055 Budapest, Falk Miksa utca 9–11.<br/>Levelezési cím: 1363 Budapest, Pf. 9.<br/>Telefon: +36 1 391 1400<br/>E-mail: <a href="mailto:ugyfelszolgalat@naih.hu" className="text-primary underline">ugyfelszolgalat@naih.hu</a><br/>Weboldal: <a href="https://www.naih.hu/" className="text-primary underline">https://www.naih.hu</a></p><p>Az érintett továbbá jogosult bírósági jogorvoslatot igénybe venni.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">23. Adatmegőrzési idők</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő személyes adatot kizárólag addig őriz, ameddig az adatkezelés céljának teljesítéséhez szükséges vagy ameddig valamely jogszabály annak megőrzését előírja.</p><p>Számlák és számviteli bizonylatok esetében a jogszabály szerinti megőrzési idő főszabály szerint legalább 8 év.</p><p>Fogyasztói panaszok és az azokra adott válaszok megőrzési ideje főszabály szerint 3 év.</p><p>Szerződéses jogviszonnyal kapcsolatos, esetleges polgári jogi igény érvényesítéséhez szükséges adat az adott körülmények függvényében a polgári jogi elévülési idő alatt kezelhető; az általános elévülési idő főszabály szerint 5 év.</p><p>Hozzájáruláson alapuló adatkezelés esetén az adatot az Adatkezelő a hozzájárulás visszavonásáig, az adatkezelési cél megszűnéséig vagy az adott adatkezelésre vonatkozó egyéb szükséges határidőig kezeli.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">24. Hatósági adatkérés</h2><div className="mt-4"><p>Jogszabályban meghatározott esetben bíróság, ügyészség, nyomozó hatóság, adóhatóság, fogyasztóvédelmi hatóság, adatvédelmi hatóság vagy más jogosult szerv az Adatkezelőt személyes adatok átadására kötelezheti.</p><p className="mt-4">Az Adatkezelő ilyen esetben kizárólag a jogszerű megkeresés teljesítéséhez szükséges adatokat és csak a szükséges mértékben adja át.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">25. A tájékoztató módosítása</h2><div className="mt-4 space-y-4"><p>Az Adatkezelő jogosult jelen Adatkezelési Tájékoztatót módosítani, különösen jogszabályváltozás, új szolgáltatás, új adatfeldolgozó, online időpontfoglaló rendszer, mobil- vagy webalkalmazás, analitikai rendszer vagy más új adatkezelési cél bevezetése esetén.</p><p>A mindenkor hatályos változat a BioCare Kozmetika weboldalán kerül közzétételre.</p><p><strong>Weboldal:</strong> <a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a><br/><strong>E-mail:</strong> <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a><br/><strong>Telefon:</strong> +36 30 146 9885</p><p><strong>Miskolczi Dominika egyéni vállalkozó</strong><br/><strong>BioCare Kozmetika</strong></p><p><strong>Hatályos: 2026. szeptember 27.</strong></p></div></section>
    </div>
  </div></main>;
}