import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/impresszum")({
  head: () => ({ meta: [
    { title: "Impresszum | BioCare Kozmetika" },
    { name: "description", content: "A BioCare Kozmetika impresszuma és kapcsolattartási adatai." },
    { property: "og:title", content: "Impresszum | BioCare Kozmetika" },
    { property: "og:description", content: "A BioCare Kozmetika impresszuma és kapcsolattartási adatai." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ] }),
  component: Impresszum,
});

function Impresszum() {
  return <main className="min-h-screen bg-background px-6 py-12 text-foreground"><div className="mx-auto max-w-3xl">
    <Link to="/" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft size={16}/> Vissza a főoldalra</Link>
    <p className="mt-20 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">BioCare Kozmetika</p>
    <h1 className="mt-4 font-display text-5xl">Impresszum</h1>
    <div className="mt-8 space-y-5 leading-relaxed text-muted-foreground">
      <p>Jelen impresszum a <strong>BioCare Kozmetika</strong> weboldalának üzemeltetőjére és szolgáltatójára vonatkozó adatokat tartalmazza.</p>
    </div>
    <div className="mt-12 space-y-10 border-t border-border pt-8 leading-relaxed text-muted-foreground">
      <section><h2 className="font-display text-3xl text-foreground">Szolgáltató adatai</h2><div className="mt-4 space-y-2"><p><strong>Szolgáltató teljes neve:</strong><br/>Miskolczi Dominika egyéni vállalkozó</p><p><strong>Kereskedelmi / fantázianév:</strong><br/>BioCare Kozmetika</p><p><strong>Alapítás éve:</strong><br/>2023</p><p><strong>Adószám:</strong><br/>59869850-1-22</p><p><strong>Főtevékenység:</strong><br/>9622 – Szépségápolás</p><p><strong>Székhely:</strong><br/>7627 Pécs, Károly utca 11. 3. ajtó</p><p><strong>Telephelyek száma:</strong><br/>1</p><p><strong>Szolgáltatás helye / telephely:</strong><br/>7622 Pécs, Jókai u. 30.</p><p><strong>Egyéni vállalkozói nyilvántartási szám:</strong><br/>[KITÖLTENDŐ]</p><p><strong>Nyilvántartást vezető hatóság:</strong><br/>Nemzeti Adó- és Vámhivatal (NAV)</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Kapcsolattartási adatok</h2><div className="mt-4 space-y-2"><p><strong>E-mail:</strong><br/><a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a></p><p><strong>Telefonszám:</strong><br/>+36 30 146 9885</p><p><strong>Weboldal:</strong><br/><a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a></p><p><strong>Kapcsolattartó:</strong><br/>Miskolczi Dominika</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">A weboldal üzemeltetője</h2><div className="mt-4 space-y-2"><p>A weboldal tartalmáért felelős szolgáltató:</p><p><strong>Miskolczi Dominika egyéni vállalkozó</strong><br/><strong>BioCare Kozmetika</strong></p><p>Székhely: 7627 Pécs, Károly utca 11. 3. ajtó<br/>Szolgáltatás helye: 7622 Pécs, Jókai u. 30.<br/>Adószám: 59869850-1-22<br/>E-mail: <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a><br/>Telefon: +36 30 146 9885<br/>Weboldal: <a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a></p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Tárhelyszolgáltató</h2><div className="mt-4 space-y-2"><p><strong>Tárhelyszolgáltató neve:</strong><br/>[KITÖLTENDŐ]</p><p><strong>Székhelye:</strong><br/>[KITÖLTENDŐ]</p><p><strong>E-mail / elérhetőség:</strong><br/>[KITÖLTENDŐ]</p><p><strong>Weboldala:</strong><br/>[KITÖLTENDŐ]</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Szerzői jogok</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika weboldalán található saját szövegek, fényképek, grafikák, arculati elemek, logók, szolgáltatásleírások és egyéb tartalmak szerzői jogi védelem alatt állhatnak.</p><p>A weboldal saját tartalmának engedély nélküli másolása, többszörözése, módosítása, terjesztése, újraközlése vagy kereskedelmi célú felhasználása nem megengedett, kivéve, ha ahhoz a jogosult előzetesen hozzájárult, vagy a felhasználást jogszabály kifejezetten lehetővé teszi.</p><p>A weboldalon esetlegesen megjelenő harmadik személyek védjegyei, márkanevei, képei és egyéb tartalmai azok jogosultjainak tulajdonát képezik.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Felelősség</h2><div className="mt-4 space-y-4"><p>A BioCare Kozmetika törekszik arra, hogy a weboldalon található információk pontosak, megfelelőek és naprakészek legyenek.</p><p>A weboldalon található kozmetikai, bőrápolási, szépségápolási és kezelésekkel kapcsolatos információk <strong>általános tájékoztató jellegűek</strong>, és nem minősülnek orvosi diagnózisnak, egészségügyi tanácsadásnak vagy orvosi kezelésnek.</p><p>Egyes kozmetikai kezelések megkezdése előtt az egyéni körülmények és esetleges ellenjavallatok felmérése szükséges lehet.</p><p>Egészségügyi probléma, betegség vagy annak gyanúja esetén megfelelő egészségügyi szakember felkeresése javasolt.</p><p>A BioCare Kozmetika nem vállal felelősséget olyan külső weboldalak tartalmáért, elérhetőségéért vagy működéséért, amelyekre a weboldalon található hivatkozás vezet, és amelyek felett a szolgáltató nem rendelkezik ellenőrzéssel.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Adatvédelem</h2><div className="mt-4 space-y-4"><p>A személyes adatok kezelésére vonatkozó részletes szabályokat a BioCare Kozmetika külön <strong>Adatkezelési és Adatvédelmi Tájékoztatója</strong> tartalmazza.</p><p>Az adatkezelési tájékoztató kiterjedhet különösen:</p><ul className="list-disc space-y-2 pl-6"><li>a kapcsolatfelvételre,</li><li>az időpontfoglalásra,</li><li>a kozmetikai szolgáltatások igénybevételére,</li><li>az esetleges egészségügyi és különleges személyes adatok kezelésére,</li><li>a számlázásra,</li><li>a weboldal működésére,</li><li>a sütikre,</li><li>az online időpontfoglalási rendszerre,</li><li>a közösségi média használatára,</li><li>valamint az érintettek adatvédelmi jogaira.</li></ul></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Online időpontfoglalás</h2><div className="mt-4 space-y-4"><p>Amennyiben a BioCare Kozmetika online időpontfoglalási rendszert vagy saját webalkalmazást üzemeltet, annak használatára a weboldalon közzétett vonatkozó felhasználási és adatvédelmi feltételek irányadók.</p><p>Külső időpontfoglalási szolgáltató igénybevétele esetén a szolgáltató adatai az Adatkezelési Tájékoztatóban kerülnek feltüntetésre.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Panaszkezelés és kapcsolatfelvétel</h2><div className="mt-4 space-y-2"><p>A szolgáltatással vagy a weboldal működésével kapcsolatos kérdés, észrevétel vagy panasz az alábbi elérhetőségeken jelezhető:</p><p><strong>BioCare Kozmetika</strong><br/>Miskolczi Dominika egyéni vállalkozó</p><p>E-mail: <a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a><br/>Telefon: +36 30 146 9885<br/>Székhely: 7627 Pécs, Károly utca 11. 3. ajtó<br/>Szolgáltatás helye: 7622 Pécs, Jókai u. 30.</p></div></section>
      <section><h2 className="font-display text-3xl text-foreground">Alkalmazandó jog</h2><div className="mt-4"><p>A weboldal működésére, a szolgáltató tevékenységére, valamint a szolgáltató és a weboldal felhasználói közötti jogviszonyra elsősorban a magyar jog és a közvetlenül alkalmazandó európai uniós jogszabályok rendelkezései irányadók.</p></div></section>
      <section className="border-t border-border pt-8"><div className="space-y-2"><p><strong>Szolgáltató:</strong><br/>Miskolczi Dominika egyéni vállalkozó</p><p><strong>Fantázianév:</strong><br/>BioCare Kozmetika</p><p><strong>Adószám:</strong><br/>59869850-1-22</p><p><strong>Székhely:</strong><br/>7627 Pécs, Károly utca 11. 3. ajtó</p><p><strong>Szolgáltatás helye:</strong><br/>7622 Pécs, Jókai u. 30.</p><p><strong>Weboldal:</strong><br/><a href="https://biocarekozmetikapecs.hu/" className="text-primary underline">https://biocarekozmetikapecs.hu</a></p><p><strong>E-mail:</strong><br/><a href="mailto:biocarekozm@gmail.com" className="text-primary underline">biocarekozm@gmail.com</a></p><p><strong>Telefon:</strong><br/>+36 30 146 9885</p><p><strong>Utolsó frissítés:</strong><br/>2026. szeptember 27.</p></div></section>
    </div>
  </div></main>;
}