import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Instagram, Facebook, Leaf, Menu, X, Sparkles, Check, Mail, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { site } from "@/lib/site-data";
import hero from "@/assets/bioker-hero.jpg";
import portrait from "@/assets/bioker-portrait.jpg";
import treatment from "@/assets/bioker-treatment.jpg";
import products from "@/assets/bioker-products.jpg";
import ritual from "@/assets/bioker-ritual.jpg";
import space from "@/assets/bioker-space.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Bioker Kozmetika | Személyre szabott szépségápolás Pécsen" },
    { name: "description", content: "Bioker Kozmetika Pécsen: személyre szabott arckezelések, természetes szépségápolás és énidő Szidónikával. Fedezd fel a kezeléseket!" },
    { property: "og:title", content: "Bioker Kozmetika | Személyre szabott szépségápolás Pécsen" },
    { property: "og:description", content: "A bőröd megérdemli a figyelmet. Természetes szépségápolás és feltöltődés Pécsen." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: Home,
});

const nav = [
  { label: "Kezelések", id: "kezelesek" }, { label: "Árak", id: "arak" },
  { label: "Rólam", id: "rolam" }, { label: "Galéria", id: "galeria" },
  { label: "Vélemények", id: "velemenyek" },
];
const gallery = [
  { src: treatment, alt: "Arcápoló kezelés hangulatképe", width: 1008, height: 1200 },
  { src: products, alt: "Természetes arcápolási termékek hangulatképe", width: 1008, height: 1200 },
  { src: space, alt: "Kozmetikai kezelőhelyiség hangulatképe", width: 1008, height: 1200 },
  { src: ritual, alt: "Kozmetikai rituálé hangulatképe", width: 1008, height: 1200 },
];

function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeReview, setActiveReview] = useState(0);
  const [activePhoto, setActivePhoto] = useState<number | null>(null);
  const [formStatus, setFormStatus] = useState("");
  useEffect(() => {
    if (activePhoto === null) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setActivePhoto(null);
      if (e.key === "ArrowRight") setActivePhoto((v) => v === null ? 0 : (v + 1) % gallery.length);
      if (e.key === "ArrowLeft") setActivePhoto((v) => v === null ? 0 : (v - 1 + gallery.length) % gallery.length);
    };
    document.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => { document.removeEventListener("keydown", onKey); document.body.style.overflow = ""; };
  }, [activePhoto]);
  useEffect(() => {
    const timer = window.setInterval(() => setActiveReview((v) => (v + 1) % site.testimonials.length), 6500);
    return () => window.clearInterval(timer);
  }, []);
  async function submitRequest(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const message = `Időpontkérés – ${site.name}\nNév: ${data.get("name")}\nE-mail: ${data.get("email")}\nTelefon: ${data.get("phone") || "Nincs megadva"}\nÉrdeklődés: ${data.get("service")}\nÜzenet: ${data.get("message") || "Nincs megadva"}`;
    if (site.email) {
      window.location.href = `mailto:${site.email}?subject=${encodeURIComponent("Időpontkérés – Bioker Kozmetika")}&body=${encodeURIComponent(message)}`;
      setFormStatus("Megnyitottuk a leveleződet. Az üzenet elküldéséhez ott kell jóváhagynod a küldést.");
    } else {
      try { await navigator.clipboard.writeText(message); setFormStatus("Az időpontkérés szövegét kimásoltuk. A foglalási elérhetőség még nincs megadva, ezért az üzenet nem lett elküldve."); }
      catch { setFormStatus("A foglalási elérhetőség még nincs megadva, ezért az üzenet nem lett elküldve."); }
    }
  }
  return <div className="overflow-x-hidden bg-background text-foreground">
    <header className="absolute inset-x-0 top-0 z-30 border-b border-hero-foreground/20 text-hero-foreground">
      <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between gap-6 px-6 md:px-10 lg:px-16">
        <a href="#top" className="flex shrink-0 items-center gap-2.5" aria-label="Bioker Kozmetika, vissza az oldal tetejére"><span className="flex size-9 items-center justify-center rounded-full border border-hero-foreground/70"><Leaf size={18} strokeWidth={1.4}/></span><span className="text-[17px] font-semibold uppercase leading-none tracking-[0.17em]">Bioker<span className="block pt-1 text-[9px] font-normal tracking-[0.34em]">Kozmetika</span></span></a>
        <nav className="hidden items-center gap-7 text-[12px] font-medium lg:flex" aria-label="Fő navigáció">{nav.map(item => <a key={item.id} href={`#${item.id}`} className="transition-opacity hover:opacity-60">{item.label}</a>)}</nav>
        <a href="#kapcsolat" className="hidden items-center gap-2 border-b border-hero-foreground pb-1 text-[12px] font-semibold md:inline-flex">Időpontot szeretnék <ArrowUpRight size={15}/></a>
        <Button variant="ghost" size="icon" className="text-hero-foreground hover:bg-hero-foreground/15 hover:text-hero-foreground lg:hidden" aria-label={menuOpen ? "Menü bezárása" : "Menü megnyitása"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</Button>
      </div>
      {menuOpen && <nav className="absolute left-0 right-0 top-20 flex flex-col gap-1 border-t border-hero-foreground/20 bg-primary px-6 py-5 shadow-xl lg:hidden" aria-label="Mobil navigáció">{[...nav, {label:"Kapcsolat",id:"kapcsolat"}].map(item => <a key={item.id} href={`#${item.id}`} onClick={() => setMenuOpen(false)} className="py-2 text-sm">{item.label}</a>)}</nav>}
    </header>

    <main id="top">
      <section className="hero relative flex min-h-[690px] items-center overflow-hidden text-hero-foreground md:min-h-[740px]" aria-label="Bioker Kozmetika">
        <img src={hero} alt="Nyugtató arcápoló kezelés természetes hangulatú környezetben" width={1600} height={1104} fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-[62%_center]"/>
        <div className="absolute inset-0 bg-hero-shade"/>
        <div className="relative mx-auto w-full max-w-[1440px] px-6 pb-16 pt-32 md:px-10 lg:px-16">
          <div className="max-w-[650px] animate-appear"><div className="mb-7 flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.25em]"><span className="h-px w-8 bg-hero-foreground/80"/> Bioker Kozmetika · Pécs</div>
            <h1 className="font-display text-[clamp(3.5rem,6.5vw,6.8rem)] leading-[1.04] font-medium">A bőröd<br/>megérdemli<br/><em className="font-normal">a figyelmet.</em></h1>
            <p className="mt-7 max-w-[435px] text-base leading-7 text-hero-foreground/90 md:text-lg">Személyre szabott szépségápolás Pécsen, ahol a ragyogó bőr és a feltöltődés találkozik.</p>
            <div className="mt-9 flex flex-wrap items-center gap-5"><Button asChild size="lg" className="h-12 rounded-none bg-primary-foreground px-7 text-xs font-semibold uppercase tracking-[0.11em] text-primary hover:bg-primary-foreground/85"><a href="#kapcsolat">Időpontfoglalás <ArrowUpRight/></a></Button><a href="#kezelesek" className="inline-flex items-center gap-2 border-b border-hero-foreground pb-1 text-xs font-semibold uppercase tracking-[0.11em]">Kezelések megtekintése <ArrowRight size={16}/></a></div>
          </div>
        </div>
        <a href="#kezelesek" className="absolute bottom-7 left-6 flex items-center gap-3 text-[11px] uppercase tracking-[0.16em] md:left-10 lg:left-16">Fedezd fel <ArrowDown size={15}/></a>
        <div className="absolute bottom-7 right-6 hidden items-center gap-2 text-[11px] uppercase tracking-[0.15em] md:flex lg:right-16"><span className="size-1.5 rounded-full bg-hero-foreground"/> Természetes szépség, személyesen</div>
      </section>

      <section className="border-b border-border bg-background px-6 py-12 md:px-10 lg:px-16"><div className="mx-auto grid max-w-[1312px] gap-8 md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center md:gap-7"><p className="text-center font-display text-2xl md:text-left">Figyelem. Nyugalom. Te.</p><span className="hidden h-10 w-px bg-border md:block"/><p className="text-center text-sm leading-6 text-muted-foreground">Minden bőr egyedi. A gondoskodás is legyen az.</p><span className="hidden h-10 w-px bg-border md:block"/><div className="flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] md:justify-end"><Leaf size={18} strokeWidth={1.5}/> Pécs, Magyarország</div></div></section>

      <section id="kezelesek" className="scroll-mt-10 bg-background px-6 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[1312px]"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">01 / Amit kínálok</p><h2 className="section-title mt-5">Egy pillanat,<br/><em>ami rólad szól.</em></h2></div><p className="max-w-[360px] text-sm leading-7 text-muted-foreground">Tudatos szépségápolás, természetes harmónia és személyes figyelem – minden kezelés egy lehetőség a megállásra.</p></div>
        <div className="grid gap-4 md:grid-cols-3">{site.services.map((service, index) => <article key={service.number} className="group glass-card relative flex min-h-[330px] flex-col justify-between overflow-hidden border border-border p-7 transition-all duration-500 hover:-translate-y-1 hover:border-primary/35 hover:shadow-[0_20px_60px_-35px_var(--primary)] md:p-9"><div className="flex items-start justify-between"><span className="font-display text-2xl text-primary/55">{service.number}</span><span className="flex size-10 items-center justify-center rounded-full border border-border text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">{index === 0 ? <Sparkles size={18} strokeWidth={1.3}/> : index === 1 ? <Leaf size={18} strokeWidth={1.3}/> : <ArrowUpRight size={18} strokeWidth={1.3}/>}</span></div><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">{service.detail}</p><h3 className="font-display text-[27px] leading-tight">{service.title}</h3><p className="mt-4 max-w-[310px] text-sm leading-7 text-muted-foreground">{service.description}</p><a href="#kapcsolat" className="mt-7 inline-flex items-center gap-2 border-b border-primary pb-1 text-xs font-semibold">Érdeklődöm <ArrowUpRight size={14}/></a></div></article>)}</div>
      </div></section>

      <section id="arak" className="scroll-mt-10 bg-secondary px-6 py-24 md:px-10 md:py-28 lg:px-16"><div className="mx-auto grid max-w-[1312px] gap-14 lg:grid-cols-[0.85fr_1.15fr] lg:gap-24"><div><p className="eyebrow">02 / Árak</p><h2 className="section-title mt-5">Átlátható<br/><em>gondoskodás.</em></h2><p className="mt-7 max-w-sm text-sm leading-7 text-muted-foreground">A kezelések mindig a bőröd aktuális igényeihez igazodnak. Az aktuális árakról érdeklődj időpontkéréskor.</p><a href="#kapcsolat" className="mt-8 inline-flex items-center gap-2 border-b border-primary pb-1 text-xs font-semibold uppercase tracking-[0.1em]">Kérj személyes ajánlatot <ArrowUpRight size={16}/></a></div><div className="border-t border-primary/20">{site.prices.map(group => <div key={group.category} className="border-b border-primary/20 py-7"><h3 className="mb-5 text-[11px] font-bold uppercase tracking-[0.18em] text-primary">{group.category}</h3>{group.items.map(item => <div key={item} className="flex items-center justify-between gap-4 py-3 text-sm md:text-base"><span>{item}</span><span className="shrink-0 text-xs text-muted-foreground">Ár egyeztetés alapján</span></div>)}</div>)}</div></div></section>

      <section id="rolam" className="scroll-mt-10 bg-background px-6 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1312px] items-center gap-14 lg:grid-cols-2 lg:gap-28"><div className="relative max-w-[570px]"><img src={portrait} alt="Illusztráció egy kozmetikusról természetes hangulatú szalonban; nem Szidónika valódi portréja" loading="lazy" width={912} height={1152} className="aspect-[4/5] w-full object-cover"/><div className="absolute -bottom-5 -right-3 bg-primary px-6 py-5 text-primary-foreground shadow-lg md:-right-7"><Leaf size={25} strokeWidth={1.2}/></div><p className="mt-8 text-xs text-muted-foreground">Illusztrációs portré · valódi fotó feltöltésére vár</p></div><div><p className="eyebrow">03 / Rólam</p><h2 className="section-title mt-5">Szia,<br/><em>Szidónika vagyok.</em></h2><div className="mt-8 h-px w-16 bg-primary/40"/><p className="mt-8 max-w-[520px] text-base leading-8 text-muted-foreground">Hiszek abban, hogy a szépségápolás több, mint egy kezelés. Idő magadra, egy mély levegő, egy pillanat, amikor igazán figyelnek rád.</p><p className="mt-5 max-w-[520px] text-base leading-8 text-muted-foreground">A Bioker Kozmetikában olyan nyugodt teret szeretnék teremteni, ahol a bőröd igényei és a te jólléted egyformán fontosak. Szeretettel várlak Pécsen.</p><p className="mt-9 font-display text-3xl italic text-primary">Szidónika</p><a href="#kapcsolat" className="mt-8 inline-flex items-center gap-2 border-b border-primary pb-1 text-xs font-semibold uppercase tracking-[0.1em]">Ismerjük meg egymást <ArrowUpRight size={16}/></a></div></div></section>

      <section id="galeria" className="scroll-mt-10 bg-secondary px-6 py-24 md:px-10 md:py-28 lg:px-16"><div className="mx-auto max-w-[1312px]"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">04 / Inspiráció</p><h2 className="section-title mt-5">A szépség<br/><em>apró pillanatai.</em></h2></div><p className="max-w-[335px] text-sm leading-7 text-muted-foreground">Hangulatképek a természetes szépségápolás világából. Kattints egy képre a nagyításhoz.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{gallery.map((photo, index) => <Button key={photo.alt} variant="ghost" onClick={() => setActivePhoto(index)} aria-label={`${photo.alt} megnyitása`} className={`group relative block h-auto w-full overflow-hidden rounded-none p-0 hover:bg-transparent ${index % 2 === 1 ? "md:mt-10" : ""}`}><img src={photo.src} alt={photo.alt} loading="lazy" width={photo.width} height={photo.height} className="aspect-[3/4] w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute bottom-4 right-4 flex size-9 items-center justify-center bg-background/85 text-primary backdrop-blur-md"><ArrowUpRight size={17}/></span></Button>)}</div><p className="mt-7 text-xs text-muted-foreground">A képek illusztrációk, nem dokumentált vendégmunkák vagy a tényleges szalon fotói.</p></div></section>

      <section id="velemenyek" className="scroll-mt-10 bg-background px-6 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1312px] gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div><p className="eyebrow">05 / Visszajelzések</p><h2 className="section-title mt-5">Szavak, amik<br/><em>megmaradnak.</em></h2><p className="mt-6 text-sm text-muted-foreground">Az idézetek bemutató szövegek; valódi vendégvéleményekre várnak.</p></div><div className="flex min-h-[270px] flex-col justify-between border-l border-primary/30 pl-7 md:pl-12" aria-live="polite"><div key={activeReview} className="animate-appear"><span className="font-display text-6xl leading-none text-primary/40">“</span><blockquote className="-mt-2 font-display text-2xl leading-snug md:text-4xl">{site.testimonials[activeReview]?.quote}</blockquote><p className="mt-7 text-xs font-semibold uppercase tracking-[0.17em] text-muted-foreground">{site.testimonials[activeReview]?.name}</p></div><div className="mt-10 flex items-center justify-between"><div className="flex gap-2">{site.testimonials.map((_, i) => <Button key={i} size="icon" variant="ghost" aria-label={`${i + 1}. vélemény`} onClick={() => setActiveReview(i)} className="size-7 rounded-none p-2 hover:bg-transparent"><span className={`block h-1 w-full ${i === activeReview ? "bg-primary" : "bg-border"}`}/></Button>)}</div><div className="flex gap-2"><Button size="icon" variant="outline" className="size-10 rounded-full" aria-label="Előző vélemény" onClick={() => setActiveReview((activeReview - 1 + site.testimonials.length) % site.testimonials.length)}><ChevronLeft size={18}/></Button><Button size="icon" variant="outline" className="size-10 rounded-full" aria-label="Következő vélemény" onClick={() => setActiveReview((activeReview + 1) % site.testimonials.length)}><ChevronRight size={18}/></Button></div></div></div></div></section>

      <section id="kapcsolat" className="scroll-mt-10 bg-primary px-6 py-24 text-primary-foreground md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1312px] gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-24"><div><p className="text-[11px] font-semibold uppercase tracking-[0.23em] text-primary-foreground/65">06 / Kapcsolat</p><h2 className="section-title mt-6">Készen állsz<br/>egy kis <em>énidőre?</em></h2><p className="mt-7 max-w-[425px] text-base leading-8 text-primary-foreground/75">Írj néhány sort, és kezdődjön a személyre szabott gondoskodás. Az aktuális lehetőségekről és árakról egyeztetünk.</p><div className="mt-12 space-y-5 text-sm">{site.address ? <p className="flex items-center gap-3"><MapPin size={18}/>{site.address}</p> : <p className="flex items-center gap-3"><MapPin size={18}/>Pécs, Magyarország</p>}{site.email && <a className="flex items-center gap-3" href={`mailto:${site.email}`}><Mail size={18}/>{site.email}</a>}{site.phone && <a className="flex items-center gap-3" href={`tel:${site.phone}`}><span>☎</span>{site.phone}</a>}</div></div><form onSubmit={submitRequest} className="grid gap-x-5 gap-y-6 border border-primary-foreground/25 bg-primary-foreground/5 p-6 backdrop-blur-md md:grid-cols-2 md:p-10"><label className="form-label">Neved *<input name="name" required autoComplete="name" placeholder="Hogy szólíthatlak?" className="form-input"/></label><label className="form-label">E-mail címed *<input name="email" required type="email" autoComplete="email" placeholder="pelda@email.hu" className="form-input"/></label><label className="form-label">Telefonszámod<input name="phone" type="tel" autoComplete="tel" placeholder="+36 ..." className="form-input"/></label><label className="form-label">Mi érdekel?<select name="service" className="form-input"><option value="Általános érdeklődés">Válassz kezelést</option>{site.services.map(service => <option key={service.number} value={service.title}>{service.title}</option>)}</select></label><label className="form-label md:col-span-2">Üzeneted<textarea name="message" rows={3} placeholder="Mesélj egy kicsit, miben segíthetek..." className="form-input resize-y"/></label><div className="md:col-span-2"><Button type="submit" size="lg" className="h-12 w-full rounded-none bg-primary-foreground text-xs font-bold uppercase tracking-[0.1em] text-primary hover:bg-primary-foreground/85 md:w-auto md:px-9">Időpontot szeretnék <ArrowUpRight/></Button><p className="mt-4 text-xs leading-5 text-primary-foreground/65">Az üzenet az e-mail alkalmazásodon keresztül küldhető el. Amíg nincs megadva fogadói cím, csak másolható.</p>{formStatus && <p role="status" className="mt-3 flex items-start gap-2 text-sm text-primary-foreground"><Check size={16} className="mt-0.5 shrink-0"/>{formStatus}</p>}</div></form></div></section>
    </main>
    <footer className="bg-footer px-6 py-16 text-footer-foreground md:px-10 lg:px-16"><div className="mx-auto max-w-[1312px]"><div className="grid gap-12 border-b border-footer-foreground/20 pb-14 md:grid-cols-[1.4fr_1fr_1fr]"><div><div className="flex items-center gap-3"><Leaf size={28} strokeWidth={1.2}/><div className="text-lg font-bold uppercase tracking-[0.14em]">Bioker <span className="block text-[10px] font-normal tracking-[0.3em]">Kozmetika</span></div></div><p className="mt-6 max-w-[270px] text-sm leading-7 text-footer-foreground/65">Személyre szabott szépségápolás és egy kis énidő Pécsen.</p></div><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.18em]">Fedezd fel</p><div className="flex flex-col items-start gap-3 text-sm text-footer-foreground/70">{nav.map(item => <a key={item.id} href={`#${item.id}`} className="hover:text-footer-foreground">{item.label}</a>)}</div></div><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.18em]">Kapcsolat</p><p className="text-sm text-footer-foreground/70">Pécs, Magyarország</p>{site.email && <a href={`mailto:${site.email}`} className="mt-3 block text-sm">{site.email}</a>}{site.phone && <a href={`tel:${site.phone}`} className="mt-3 block text-sm">{site.phone}</a>}<div className="mt-6 flex gap-4">{site.instagram && <a href={site.instagram} aria-label="Instagram" target="_blank" rel="noreferrer"><Instagram size={19}/></a>}{site.facebook && <a href={site.facebook} aria-label="Facebook" target="_blank" rel="noreferrer"><Facebook size={19}/></a>}</div></div></div><div className="flex flex-col justify-between gap-5 pt-6 text-xs text-footer-foreground/55 md:flex-row"><p>© {new Date().getFullYear()} Bioker Kozmetika. Minden jog fenntartva.</p><div className="flex gap-6"><Link to="/adatvedelem" className="hover:text-footer-foreground">Adatvédelem</Link><Link to="/impresszum" className="hover:text-footer-foreground">Impresszum</Link><a href="#top" className="flex items-center gap-1 hover:text-footer-foreground">Vissza a tetejére <ArrowUpRight size={13}/></a></div></div></div></footer>
    {activePhoto !== null && <div role="dialog" aria-modal="true" aria-label="Képgaléria" className="fixed inset-0 z-50 flex items-center justify-center bg-overlay p-4 md:p-12" onClick={() => setActivePhoto(null)}><Button variant="ghost" size="icon" aria-label="Bezárás" onClick={() => setActivePhoto(null)} className="absolute right-5 top-5 z-10 text-hero-foreground hover:bg-hero-foreground/20 hover:text-hero-foreground"><X/></Button><Button variant="ghost" size="icon" aria-label="Előző kép" onClick={e => {e.stopPropagation();setActivePhoto((activePhoto - 1 + gallery.length) % gallery.length);}} className="absolute left-3 z-10 text-hero-foreground hover:bg-hero-foreground/20 hover:text-hero-foreground md:left-8"><ChevronLeft/></Button><img onClick={e => e.stopPropagation()} src={gallery[activePhoto]?.src} alt={gallery[activePhoto]?.alt} className="max-h-[85vh] max-w-[82vw] object-contain"/><Button variant="ghost" size="icon" aria-label="Következő kép" onClick={e => {e.stopPropagation();setActivePhoto((activePhoto + 1) % gallery.length);}} className="absolute right-3 z-10 text-hero-foreground hover:bg-hero-foreground/20 hover:text-hero-foreground md:right-8"><ChevronRight/></Button><span className="absolute bottom-4 text-xs text-hero-foreground">{activePhoto + 1} / {gallery.length}</span></div>}
  </div>;
}
