/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdatvedelemRouteImport } from './routes/adatvedelem'
import { Route as ImpresszumRouteImport } from './routes/impresszum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatvedelemRoute = AdatvedelemRouteImport.update({
  id: '/adatvedelem',
  path: '/adatvedelem',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpresszumRoute = ImpresszumRouteImport.update({
  id: '/impresszum',
  path: '/impresszum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/impresszum': typeof ImpresszumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/impresszum': typeof ImpresszumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/impresszum': typeof ImpresszumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adatvedelem' | '/impresszum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adatvedelem' | '/impresszum'
  id: '__root__' | '/' | '/adatvedelem' | '/impresszum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatvedelemRoute: typeof AdatvedelemRoute
  ImpresszumRoute: typeof ImpresszumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatvedelem': {
      id: '/adatvedelem'
      path: '/adatvedelem'
      fullPath: '/adatvedelem'
      preLoaderRoute: typeof AdatvedelemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impresszum': {
      id: '/impresszum'
      path: '/impresszum'
      fullPath: '/impresszum'
      preLoaderRoute: typeof ImpresszumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatvedelemRoute: AdatvedelemRoute,
  ImpresszumRoute: ImpresszumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
